// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Well_Readings.Data;

#nullable disable

namespace Well_Readings.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428163105_UpdateScadaHistoryPoint")]
    partial class UpdateScadaHistoryPoint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Well", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wells");
                });

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("time");

                    b.Property<Guid?>("FiltrationPlantReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FiltrationPlantReadingId");

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("Well_Readings.Models.FiltrationPlantReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Chlorine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FlowRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Turbidity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FiltrationPlantReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.Plant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Well_Readings.Models.ScadaHistoryPoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Value")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Location", "MetricType");

                    b.ToTable("ScadaHistoryPoints");
                });

            modelBuilder.Entity("Well_Readings.Models.WellAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("HighLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LowLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("WellAlarms");
                });

            modelBuilder.Entity("Well_Readings.Models.WellAlarmConfig", b =>
                {
                    b.Property<Guid>("WellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HighThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAlarmTime")
                        .HasColumnType("datetime2");

                    b.HasKey("WellId");

                    b.ToTable("WellAlarmConfigs");
                });

            modelBuilder.Entity("Well_Readings.Models.WellReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AlarmThreshold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chlorine")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid?>("DailyEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAlarm")
                        .HasColumnType("bit");

                    b.Property<decimal>("MeterReading")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("Ph")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("Phosphate")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid?>("PlantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WellId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DailyEntryId");

                    b.HasIndex("PlantId");

                    b.HasIndex("WellId");

                    b.HasIndex("WellId1");

                    b.ToTable("WellReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.HasOne("Well_Readings.Models.FiltrationPlantReading", "FiltrationPlantReading")
                        .WithMany()
                        .HasForeignKey("FiltrationPlantReadingId");

                    b.Navigation("FiltrationPlantReading");
                });

            modelBuilder.Entity("Well_Readings.Models.WellReading", b =>
                {
                    b.HasOne("Well_Readings.Models.DailyEntry", "DailyEntry")
                        .WithMany("WellReadings")
                        .HasForeignKey("DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Well_Readings.Models.Plant", null)
                        .WithMany("Readings")
                        .HasForeignKey("PlantId");

                    b.HasOne("Well", "Well")
                        .WithMany()
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Well", null)
                        .WithMany("WellReadings")
                        .HasForeignKey("WellId1");

                    b.Navigation("DailyEntry");

                    b.Navigation("Well");
                });

            modelBuilder.Entity("Well", b =>
                {
                    b.Navigation("WellReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.Navigation("WellReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.Plant", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
