// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Well_Readings.Data;

#nullable disable

namespace Well_Readings.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414154241_AddWellReadings")]
    partial class AddWellReadings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("Well_Readings.Models.WellReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Chlorine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DailyEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MeterReading")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ph")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Phosphate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DailyEntryId");

                    b.ToTable("WellReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.WellReading", b =>
                {
                    b.HasOne("Well_Readings.Models.DailyEntry", "DailyEntry")
                        .WithMany("WellReadings")
                        .HasForeignKey("DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyEntry");
                });

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.Navigation("WellReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
