// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Well_Readings.Data;

#nullable disable

namespace Well_Readings.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422120144_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Well", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wells");
                });

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EntryTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("Well_Readings.Models.FiltrationPlantReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Chlorine")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid>("DailyEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FilterPlantMeterReading")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("MtJeffersonMeterReading")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("Ph")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal?>("Phosphate")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.HasKey("Id");

                    b.HasIndex("DailyEntryId")
                        .IsUnique();

                    b.ToTable("FiltrationPlantReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.WellReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Chlorine")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid>("DailyEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("MeterReading")
                        .HasPrecision(18)
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("Ph")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal?>("Phosphate")
                        .HasPrecision(3, 1)
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DailyEntryId");

                    b.HasIndex("WellId");

                    b.ToTable("WellReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.FiltrationPlantReading", b =>
                {
                    b.HasOne("Well_Readings.Models.DailyEntry", "DailyEntry")
                        .WithOne("FiltrationPlantReading")
                        .HasForeignKey("Well_Readings.Models.FiltrationPlantReading", "DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyEntry");
                });

            modelBuilder.Entity("Well_Readings.Models.WellReading", b =>
                {
                    b.HasOne("Well_Readings.Models.DailyEntry", "DailyEntry")
                        .WithMany("WellReadings")
                        .HasForeignKey("DailyEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Well", "Well")
                        .WithMany("WellReadings")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyEntry");

                    b.Navigation("Well");
                });

            modelBuilder.Entity("Well", b =>
                {
                    b.Navigation("WellReadings");
                });

            modelBuilder.Entity("Well_Readings.Models.DailyEntry", b =>
                {
                    b.Navigation("FiltrationPlantReading");

                    b.Navigation("WellReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
