name: Build and Publish Docker Image

on:
  push:
    branches:
      - Main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./Well Readings
          file: ./Well Readings/Dockerfile
          push: true
          tags: ghcr.io/ncbrandon/well-readings-app:latest
